# Generated by Django 5.0.6 on 2025-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
            preserve_default=False,
        ),
    ]
