# Generated by Django 5.0.6 on 2025-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_outflow_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
